export const SET_DATA_LOADING = 'PL_SET_DATA_LOADING';
export const OPEN_PRODUCT_INPUT_AREA_IN_CREATE_MODE =
  'PL_OPEN_PRODUCT_INPUT_AREA_IN_CREATE_MODE';
export const OPEN_PRODUCT_INPUT_AREA_IN_EDIT_MODE =
  'PL_OPEN_PRODUCT_INPUT_AREA_IN_EDIT_MODE';
export const HIDE_PRODUCT_INPUT_AREA = 'PL_HIDE_PRODUCT_INPUT_AREA';
export const OPEN_ADD_CATEGORY_DIALOG = 'PL_OPEN_ADD_CATEGORY_DIALOG';
export const CLOSE_ADD_CATEGORY_DIALOG = 'PL_CLOSE_ADD_CATEGORY_DIALOG';
export const OPEN_EDIT_CATEGORY_DIALOG = 'PL_OPEN_EDIT_CATEGORY_DIALOG';
export const CLOSE_EDIT_CATEGORY_DIALOG = 'PL_CLOSE_EDIT_CATEGORY_DIALOG';
export const OPEN_ADD_UNIT_DIALOG = 'PL_OPEN_ADD_UNIT_DIALOG';
export const CLOSE_ADD_UNIT_DIALOG = 'PL_CLOSE_ADD_UNIT_DIALOG';
export const OPEN_EDIT_UNIT_DIALOG = 'PL_OPEN_EDIT_UNIT_DIALOG';
export const CLOSE_EDIT_UNIT_DIALOG = 'PL_CLOSE_EDIT_UNIT_DIALOG';
export const OPEN_REMOVE_PRODUCT_DIALOG = 'PL_OPEN_REMOVE_PRODUCT_DIALOG';
export const CLOSE_REMOVE_PRODUCT_DIALOG = 'PL_CLOSE_REMOVE_PRODUCT_DIALOG';
export const SET_USED_CATEGORIES = 'PL_SET_USED_CATEGORIES';
export const SET_SELECTED_CATEGORY_ID = 'PL_SET_SELECTED_CATEGORY_ID';
export const SET_SELECTED_CATEGORY_ID_FOR_CATEGORIES_LIST =
  'PL_SET_SELECTED_CATEGORY_ID_FOR_CATEGORIES_LIST';
export const SET_SELECTED_CATEGORY_ID_FOR_PRODUCTS_LIST =
  'PL_SET_SELECTED_CATEGORY_ID_FOR_PRODUCTS_LIST';
export const SET_SHARE_BUTTON_VISIBILITY = 'PL_SET_SHARE_BUTTON_VISIBILITY';
export const SET_SHARE_PANEL_VISIBILITY = 'PL_SET_SHARE_PANEL_VISIBILITY';
export const SET_RENAME_LIST_DIALOG_VISIBILITY =
  'PL_SET_RENAME_LIST_DIALOG_VISIBILITY';
export const SET_REMOVE_ALL_PRODUCTS_DIALOG_VISIBILITY =
  'PL_SET_REMOVE_ALL_PRODUCTS_DIALOG_VISIBILITY';
export const SET_PRODUCTS_LIST_CATEGORY_UPDATING_COMPLETE =
  'PL_SET_PRODUCTS_LIST_CATEGORY_UPDATING_COMPLETE';
export const SET_REMOVE_ALL_BOUGHT_PRODUCTS_DIALOG_VISIBILITY =
  'PL_SET_REMOVE_ALL_BOUGHT_PRODUCTS_DIALOG_VISIBILITY';
export const SET_REMOVE_ALL_CATEGORY_PRODUCTS_DIALOG_VISIBILITY =
  'PL_SET_REMOVE_ALL_CATEGORY_PRODUCTS_DIALOG_VISIBILITY';
