export const SET_DATA_LOADING = 'PL_SET_DATA_LOADING';
export const OPEN_PRODUCT_INPUT_AREA_IN_CREATE_MODE =
  'PL_OPEN_PRODUCT_INPUT_AREA_IN_CREATE_MODE';
export const OPEN_PRODUCT_INPUT_AREA_IN_EDIT_MODE =
  'PL_OPEN_PRODUCT_INPUT_AREA_IN_EDIT_MODE';
export const HIDE_PRODUCT_INPUT_AREA = 'PL_HIDE_PRODUCT_INPUT_AREA';
export const OPEN_ADD_CATEGORY_DIALOG = 'PL_OPEN_ADD_CATEGORY_DIALOG';
export const CLOSE_ADD_CATEGORY_DIALOG = 'PL_CLOSE_ADD_CATEGORY_DIALOG';
export const OPEN_EDIT_CATEGORY_DIALOG = 'PL_OPEN_EDIT_CATEGORY_DIALOG';
export const CLOSE_EDIT_CATEGORY_DIALOG = 'PL_CLOSE_EDIT_CATEGORY_DIALOG';
export const OPEN_ADD_UNIT_DIALOG = 'PL_OPEN_ADD_UNIT_DIALOG';
export const CLOSE_ADD_UNIT_DIALOG = 'PL_CLOSE_ADD_UNIT_DIALOG';
export const OPEN_EDIT_UNIT_DIALOG = 'PL_OPEN_EDIT_UNIT_DIALOG';
export const CLOSE_EDIT_UNIT_DIALOG = 'PL_CLOSE_EDIT_UNIT_DIALOG';
export const OPEN_REMOVE_PRODUCT_DIALOG = 'PL_OPEN_REMOVE_PRODUCT_DIALOG';
export const CLOSE_REMOVE_PRODUCT_DIALOG = 'PL_CLOSE_REMOVE_PRODUCT_DIALOG';
export const SET_USED_CATEGORIES = 'PL_SET_USED_CATEGORIES';
export const SET_SELECTED_CATEGORY_ID = 'PL_SET_SELECTED_CATEGORY_ID';
export const ADD_SELECTED_CATEGORY_ID = 'PL_ADD_SELECTED_CATEGORY_ID';
export const REMOVE_SELECTED_CATEGORY_ID = 'PL_REMOVE_SELECTED_CATEGORY_ID';
