export const CLEAR_PRODUCTS_SUGGESTIONS = 'PS_CLEAR_PRODUCTS_SUGGESTIONS';
export const SUGGEST_PRODUCTS = 'PS_SUGGEST_PRODUCTS';
export const SUGGEST_PRODUCTS_BEGIN = 'PS_SUGGEST_PRODUCTS_BEGIN';
export const SUGGEST_PRODUCTS_FINISHED = 'PS_SUGGEST_PRODUCTS_FINISHED';
export const SUGGEST_PRODUCTS_ERROR = 'PS_SUGGEST_PRODUCTS_ERROR';
