export const CLEAR_PRODUCTS_SUGGESTIONS = 'PS_CLEAR_PRODUCTS_SUGGESTIONS';

export const CLEAR_INPUT_BASED_PRODUCTS_SUGGESTIONS =
  'PS_CLEAR_INPUT_BASED_PRODUCTS_SUGGESTIONS';
export const SUGGEST_PRODUCTS_BASED_ON_INPUT =
  'PS_SUGGEST_PRODUCTS_BASED_ON_INPUT';
export const SUGGEST_PRODUCTS_BASED_ON_INPUT_BEGIN =
  'PS_SUGGEST_PRODUCTS_BASED_ON_INPUT_BEGIN';
export const SUGGEST_PRODUCTS_BASED_ON_INPUT_FINISHED =
  'PS_SUGGEST_PRODUCTS_BASED_ON_FINISHED';
export const SUGGEST_PRODUCTS_BASED_ON_INPUT_ERROR =
  'PS_SUGGEST_PRODUCTS_BASED_ON_INPUT_ERROR';

export const CLEAR_RANDOM_PRODUCTS_SUGGESTIONS =
  'PS_CLEAR_RANDOM_PRODUCTS_SUGGESTIONS';
export const SUGGEST_RANDOM_PRODUCTS = 'PS_SUGGEST_RANDOM_PRODUCTS';
export const SUGGEST_RANDOM_PRODUCTS_BEGIN = 'PS_SUGGEST_RANDOM_PRODUCTS_BEGIN';
export const SUGGEST_RANDOM_PRODUCTS_FINISHED =
  'PS_SUGGEST_RANDOM_PRODUCTS_FINISHED';
export const SUGGEST_RANDOM_PRODUCTS_ERROR = 'PS_SUGGEST_RANDOM_PRODUCTS_ERROR';
