export const CLEAR_PRODUCTS_SUGGESTIONS = 'PS_CLEAR_PRODUCTS_SUGGESTIONS';
export const SUGGEST_PRODUCTS = 'PS_SUGGEST_PRODUCTS';
export const SUGGEST_PRODUCTS_BEGIN = 'PS_SUGGEST_PRODUCTS_BEGIN';
export const SUGGEST_PRODUCTS_FINISHED = 'PS_SUGGEST_PRODUCTS_FINISHED';
export const SUGGEST_PRODUCTS_ERROR = 'PS_SUGGEST_PRODUCTS_ERROR';

export const SUGGEST_PRODUCTS_BASED_ON_CURRENT_PRODUCTS_LIST =
  'PS_SUGGEST_PRODUCTS_BASED_ON_CURRENT_PRODUCTS_LIST';
export const SUGGEST_PRODUCTS_BASED_ON_CURRENT_PRODUCTS_LIST_BEGIN =
  'PS_SUGGEST_PRODUCTS_BASED_ON_CURRENT_PRODUCTS_LIST_BEGIN';
export const SUGGEST_PRODUCTS_BASED_ON_CURRENT_PRODUCTS_LIST_FINISHED =
  'PS_SUGGEST_PRODUCTS_BASED_ON_CURRENT_PRODUCTS_LIST_FINISHED';
export const SUGGEST_PRODUCTS_BASED_ON_CURRENT_PRODUCTS_LIST_ERROR =
  'PS_SUGGEST_PRODUCTS_BASED_ON_CURRENT_PRODUCTS_LIST_ERROR';

export const SUGGEST_PRODUCTS_BASED_ON_PARTIAL_INPUT =
  'PS_SUGGEST_PRODUCTS_BASED_ON_PARTIAL_INPUT';
export const SUGGEST_PRODUCTS_BASED_ON_PARTIAL_INPUT_BEGIN =
  'PS_SUGGEST_PRODUCTS_BASED_ON_PARTIAL_INPUT_BEGIN';
export const SUGGEST_PRODUCTS_BASED_ON_PARTIAL_INPUT_FINISHED =
  'PS_SUGGEST_PRODUCTS_BASED_ON_PARTIAL_INPUT_FINISHED';
export const SUGGEST_PRODUCTS_BASED_ON_PARTIAL_INPUT_ERROR =
  'PS_SUGGEST_PRODUCTS_BASED_ON_PARTIAL_INPUT_ERROR';
