const categoriesTableInitialData = {
  idPrefix: Number.MAX_SAFE_INTEGER,
  categories: [
    {
      id: Number.MAX_SAFE_INTEGER - 1,
      name: 'Другое',
      color: '#c0c0c0',
      createTimestamp: 10,
      updateTimestamp: 10,
      editable: 0,
      deleted: 0,
      translationMark: 'categories_other',
      default: true,
    },
    {
      id: Number.MAX_SAFE_INTEGER - 2,
      name: 'Продукты',
      color: '#00cc00',
      createTimestamp: 9,
      updateTimestamp: 9,
      editable: 0,
      deleted: 0,
      translationMark: 'categories_products',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 3,
      name: 'Хозтовары',
      color: '#009999',
      createTimestamp: 8,
      updateTimestamp: 8,
      editable: 0,
      deleted: 0,
      translationMark: 'categories_household_goods',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 4,
      name: 'Одежда и обувь',
      color: '#993300',
      createTimestamp: 7,
      updateTimestamp: 7,
      editable: 0,
      deleted: 0,
      translationMark: 'categories_clothing_and_shoes',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 5,
      name: 'Электроника',
      color: '#0073e6',
      createTimestamp: 6,
      updateTimestamp: 6,
      editable: 0,
      deleted: 0,
      translationMark: 'categories_electronics',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 6,
      name: 'Авто',
      // color: '#3399ff',
      // color: '#33cccc',
      color: '#ffff00',
      createTimestamp: 5,
      updateTimestamp: 5,
      editable: 0,
      deleted: 0,
      translationMark: 'categories_car',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 10,
      name: 'Игрушки',
      color: '#ff8000',
      createTimestamp: 1,
      updateTimestamp: 1,
      editable: 0,
      deleted: 0,
      translationMark: 'categories_toys',
    },
  ],
};

export default categoriesTableInitialData;

// {
//   id: Number.MAX_SAFE_INTEGER - 8,
//   name: 'Красота и здоровье',
//   color: '#ff0066',
//   createTimestamp: 3,
//   updateTimestamp: 3,
//   editable: 0,
//   deleted: 0,
//   translationMark: 'categories_beauty_and_health',
// },
// {
//   id: Number.MAX_SAFE_INTEGER - 9,
//   name: 'Спорт и отдых',
//   color: '#ffccff',
//   createTimestamp: 2,
//   updateTimestamp: 2,
//   editable: 0,
//   deleted: 0,
//   translationMark: 'categories_sport_and_vacation',
// },
// {
//   id: Number.MAX_SAFE_INTEGER - 7,
//   name: 'Досуг и хобби',
//   color: '#99d6ff',
//   createTimestamp: 4,
//   updateTimestamp: 4,
//   editable: 0,
//   deleted: 0,
//   translationMark: 'categories_hobby',
// },
// {
//   id: Number.MAX_SAFE_INTEGER - 4,
//   name: 'Товары для дома',
//   color: '#ffff00',
//   createTimestamp: 4,
//   updateTimestamp: 4,
//   editable: 0,
//   deleted: 0,
//   translationMark: 'categories_homewares',
// },
// {
//   id: Number.MAX_SAFE_INTEGER - 5,
//   name: 'Мебель',
//   color: '#663300',
//   createTimestamp: 5,
//   updateTimestamp: 5,
//   editable: 0,
//   deleted: 0,
//   translationMark: 'categories_furniture',
// },
// {
//   id: Number.MAX_SAFE_INTEGER - 13,
//   name: 'Дача и сад',
//   color: '#00cc66',
//   createTimestamp: 13,
//   updateTimestamp: 13,
//   editable: 0,
//   deleted: 0,
//   translationMark: 'categories_garden',
// },
// {
//   id: Number.MAX_SAFE_INTEGER - 14,
//   name: 'Ремонт',
//   color: '#476b6b',
//   createTimestamp: 14,
//   updateTimestamp: 14,
//   editable: 0,
//   deleted: 0,
//   translationMark: 'categories_repair',
// },
// {
//   id: Number.MAX_SAFE_INTEGER - 15,
//   name: 'Зоотовары',
//   color: '#ffffcc',
//   createTimestamp: 15,
//   updateTimestamp: 15,
//   editable: 0,
//   deleted: 0,
//   translationMark: 'categories_pet',
// },
// {
//   id: Number.MAX_SAFE_INTEGER - 16,
//   name: 'Канцтовары',
//   color: '#339966',
//   createTimestamp: 16,
//   updateTimestamp: 16,
//   editable: 0,
//   deleted: 0,
//   translationMark: 'categories_office_supplies',
// },
// {
//   id: Number.MAX_SAFE_INTEGER - 17,
//   name: 'Книги',
//   color: '#993300',
//   createTimestamp: 17,
//   updateTimestamp: 17,
//   editable: 0,
//   deleted: 0,
//   translationMark: 'categories_books',
// },
// {
//   id: Number.MAX_SAFE_INTEGER - 7,
//   name: 'Бытовая техника',
//   color: '#99ccff',
//   createTimestamp: 7,
//   updateTimestamp: 7,
//   editable: 0,
//   deleted: 0,
//   translationMark: 'categories_home_appliances',
// },
