import {StyleSheet} from 'react-native';

export const productsListViewStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#edeef1',
  },
  productCategoriesContainer: {
    alignSelf: 'stretch',
    height: 40,
    marginTop: 4,
    marginLeft: 4,
    marginRight: 4,
    flexDirection: 'row-reverse',
  },
  loadingIndicatorContainer: {
    alignSelf: 'stretch',
    alignItems: 'center',
    height: 10,
  },
  addShoppingListItemButtonContainer: {
    position: 'absolute',
    bottom: 0,
    marginBottom: 10,
    zIndex: 10,
  },
  addShoppingListItemButton: {},
  shareButtonContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    marginBottom: 20,
    marginRight: 15,
    zIndex: 10,
  },
  emptyShoppingListScreenContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 83,
  },
  nonEmptyShoppingListScreenContent: {
    flex: 1,
    alignSelf: 'stretch',
  },
  shoppingListContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    // marginLeft: 8,
    // marginRight: 8,
  },
  inputAreaContainer: {
    alignSelf: 'stretch',
    height: 150,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  shadedBackground: {
    backgroundColor: 'black',
    opacity: 0.5,
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  bottomGradient: {
    bottom: 0,
    left: 0,
    right: 0,
    height: 110,
    position: 'absolute',
  },
  sharePanel: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    marginBottom: 90,
    marginRight: 15,
    zIndex: 10,
  },
});
