export const LOAD_UNITS = 'U_LOAD_UNITS';
export const LOAD_UNITS_BEGIN = 'U_LOAD_UNITS_BEGIN';
export const LOAD_UNITS_FINISHED = 'U_LOAD_UNITS_FINISHED';
export const LOAD_UNITS_ERROR = 'U_LOAD_UNITS_ERROR';
