const InitializeAppHookLocalActionTypes = {
  SET_APP_IS_VISIBLE: 'IAHLA_SET_APP_IS_VISIBLE',
  SET_SERVICES_IS_READY: 'IAHLA_SET_SERVICES_IS_READY',
  SET_LOADING_COMMANDS: 'IAHLA_SET_LOADING_COMMANDS',
  SET_NAVIGATION_COMMANDS: 'IAHLA_SET_NAVIGATION_COMMANDS',
  SET_SHOPPING_LIST_MODIFICATION_COMMANDS:
    'IAHLA_SET_SHOPPING_LIST_MODIFICATION_COMMANDS',
};

export default InitializeAppHookLocalActionTypes;
