export const LOAD_PRODUCTS_LIST = 'PL_LOAD_PRODUCTS_LIST';
export const LOAD_PRODUCTS_LIST_BEGIN = 'PL_LOAD_PRODUCTS_LIST_BEGIN';
export const LOAD_PRODUCTS_LIST_FINISHED = 'PL_LOAD_PRODUCTS_LIST_FINISHED';
export const LOAD_PRODUCTS_LIST_ERROR = 'PL_LOAD_PRODUCTS_LIST_ERROR';
export const CLEAR_PRODUCTS_LIST_CACHED_DATA =
  'PL_CLEAR_PRODUCTS_LIST_CACHED_DATA';
export const ADD_PRODUCT = 'PL_ADD_PRODUCT';
export const ADD_PRODUCT_BEGIN = 'PL_ADD_PRODUCT_BEGIN';
export const ADD_PRODUCT_CREATED = 'PL_ADD_PRODUCT_CREATED';
export const ADD_PRODUCT_CONFIRMED = 'PL_ADD_PRODUCT_CONFIRMED';
export const ADD_PRODUCT_ERROR = 'PL_ADD_PRODUCT_ERROR';
