export const CREATE_SHOPPING_LIST = 'SL_CREATE_SHOPPING_LIST';
export const CREATE_SHOPPING_LIST_BEGIN = 'SL_CREATE_SHOPPING_LIST_BEGIN';
export const CREATE_SHOPPING_LIST_FINISHED = 'SL_CREATE_SHOPPING_LIST_FINISHED';
export const CREATE_SHOPPING_LIST_ERROR = 'SL_CREATE_SHOPPING_LIST_ERROR';
export const RESET_CREATE_SHOPPING_LIST_STATUS =
  'SL_RESET_CREATE_SHOPPING_LIST_STATUS';
export const LOAD_SHOPPING_LISTS = 'SL_LOAD_SHOPPING_LISTS';
export const LOAD_SHOPPING_LISTS_BEGIN = 'SL_LOAD_SHOPPING_LISTS_BEGIN';
export const LOAD_SHOPPING_LISTS_FINISHED = 'SL_LOAD_SHOPPING_LISTS_FINISHED';
export const LOAD_SHOPPING_LISTS_ERROR = 'SL_LOAD_SHOPPING_LISTS_ERROR';
export const UPDATE_SHOPPING_LISTS = 'SL_UPDATE_SHOPPING_LISTS';
export const UPDATE_SHOPPING_LISTS_BEGIN = 'SL_UPDATE_SHOPPING_LISTS_BEGIN';
export const UPDATE_SHOPPING_LISTS_FINISHED =
  'SL_UPDATE_SHOPPING_LISTS_FINISHED';
export const UPDATE_SHOPPING_LISTS_ERROR = 'SL_UPDATE_SHOPPING_LISTS_ERROR';
export const REMOVE_SHOPPING_LIST = 'SL_REMOVE_SHOPPING_LIST';
export const REMOVE_SHOPPING_LIST_BEGIN = 'SL_REMOVE_SHOPPING_LIST_BEGIN';
export const REMOVE_SHOPPING_LIST_FINISHED = 'SL_REMOVE_SHOPPING_LIST_FINISHED';
export const REMOVE_SHOPPING_LIST_ERROR = 'SL_REMOVE_SHOPPING_LIST_ERROR';
