export const SET_SHARE_AVAILABILITY = 'SET_SHARE_AVAILABILITY';
export const CHECK_SHARE_AVAILABILITY = 'CHECK_SHARE_AVAILABILITY';
export const CHECK_SHARE_AVAILABILITY_BEGIN = 'CHECK_SHARE_AVAILABILITY_BEGIN';
export const CHECK_SHARE_AVAILABILITY_ERROR = 'CHECK_SHARE_AVAILABILITY_ERROR';
export const SHARE_PRODUCTS_LIST_VIA_APP = 'SHARE_PRODUCTS_LIST_VIA_APP';
export const SHARE_PRODUCTS_LIST_VIA_APP_BEGIN =
  'SHARE_PRODUCTS_LIST_VIA_APP_BEGIN';
export const SHARE_PRODUCTS_LIST_VIA_APP_FINISHED =
  'SHARE_PRODUCTS_LIST_VIA_APP_FINISHED';
export const SHARE_PRODUCTS_LIST_VIA_APP_ERROR =
  'SHARE_PRODUCTS_LIST_VIA_APP_ERROR';
