export const SET_SHARE_AVAILABILITY = 'SET_SHARE_AVAILABILITY';
export const CHECK_SHARE_AVAILABILITY = 'CHECK_SHARE_AVAILABILITY';
export const CHECK_SHARE_AVAILABILITY_BEGIN = 'CHECK_SHARE_AVAILABILITY_BEGIN';
export const CHECK_SHARE_AVAILABILITY_ERROR = 'CHECK_SHARE_AVAILABILITY_ERROR';
