export const LOAD_CATEGORIES = 'C_LOAD_CATEGORIES';
export const LOAD_CATEGORIES_BEGIN = 'C_LOAD_CATEGORIES_BEGIN';
export const LOAD_CATEGORIES_FINISHED = 'C_LOAD_CATEGORIES_FINISHED';
export const LOAD_CATEGORIES_ERROR = 'C_LOAD_CATEGORIES_ERROR';
