export const LOAD_CATEGORIES = 'C_LOAD_CATEGORIES';
export const LOAD_CATEGORIES_BEGIN = 'C_LOAD_CATEGORIES_BEGIN';
export const LOAD_CATEGORIES_FINISHED = 'C_LOAD_CATEGORIES_FINISHED';
export const LOAD_CATEGORIES_ERROR = 'C_LOAD_CATEGORIES_ERROR';
export const ADD_CATEGORY = 'C_ADD_CATEGORY';
export const ADD_CATEGORY_BEGIN = 'C_ADD_CATEGORY_BEGIN';
export const ADD_CATEGORY_FINISHED = 'C_ADD_CATEGORY_FINISHED';
export const ADD_CATEGORY_ERROR = 'C_ADD_CATEGORY_ERROR';
