export const SET_WIDGET_INITIAL_STATE = 'AWT_SET_WIDGET_INITIAL_STATE';
export const SET_WIDGET_IS_ACTIVE_STATUS = 'AWT_SET_WIDGET_IS_ACTIVE_STATUS';
export const SET_WIDGET_SHOPPING_LIST = 'AWT_SET_WIDGET_SHOPPING_LIST';
export const WIDGET_SHOPPING_LIST_SET = 'AWT_WIDGET_SHOPPING_LIST_SET';
