const AppWidgetActionTypes = {
  SET_REQUESTED_TO_OPEN_SHOPPING_LIST_ID:
    'AWAT_SET_REQUESTED_TO_OPEN_SHOPPING_LIST_ID',
  RESET_REQUESTED_TO_OPEN_SHOPPING_LIST_ID:
    'AWAT_RESET_REQUESTED_TO_OPEN_SHOPPING_LIST_ID',
  HANDLE_CHANGE_PRODUCT_STATUS_WIDGET_REQUEST:
    'AWAT_HANDLE_CHANGE_PRODUCT_STATUS_WIDGET_REQUEST',
};

export default AppWidgetActionTypes;
