export const LOCATE_PRODUCT = 'PSL_LOCATE_PRODUCT';
export const LOCATE_PRODUCT_BEGIN = 'PSL_LOCATE_PRODUCT_BEGIN';
export const LOCATE_PRODUCT_FINISHED = 'PSL_LOCATE_PRODUCT_FINISHED';
export const LOCATE_PRODUCT_ERROR = 'PSL_LOCATE_PRODUCT_ERROR';
