export const SELECT_PRODUCT_NAME = 'PIA_SELECT_PRODUCT_NAME';
export const SELECT_PRODUCT_QUANTITY = 'PIA_SELECT_PRODUCT_QUANTITY';
export const SELECT_PRODUCT_NOTE = 'PIA_SELECT_PRODUCT_NOTE';
export const SET_PRODUCT_NAME = 'PIA_SET_PRODUCT_NAME';
export const SET_QUANTITY = 'PIA_SET_QUANTITY';
export const SET_NOTE = 'PIA_SET_NOTE';
export const SUBMIT_VALUES = 'PIA_SUBMIT_VALUES';
