export const HIDE_INPUT_AREA = 'PIA_HIDE_INPUT_AREA';
export const SET_PREDEFINED_STATE = 'PIA_SET_PREDEFINED_STATE';
export const SET_PREDEFINED_DATA = 'PIA_SET_PREDEFINED_DATA';
export const SELECT_PRODUCT_NAME = 'PIA_SELECT_PRODUCT_NAME';
export const SELECT_PRODUCT_QUANTITY = 'PIA_SELECT_PRODUCT_QUANTITY';
export const SELECT_PRODUCT_NOTE = 'PIA_SELECT_PRODUCT_NOTE';
export const SET_PRODUCT_NAME = 'PIA_SET_PRODUCT_NAME';
export const SET_QUANTITY = 'PIA_SET_QUANTITY';
export const SET_NOTE = 'PIA_SET_NOTE';
export const SET_CATEGORY = 'PIA_SET_CATEGORY';
export const SET_UNIT = 'PIA_SET_UNIT';
export const SUBMIT_VALUES = 'PIA_SUBMIT_VALUES';
export const SET_PRODUCT_SUGGESTIONS = 'PIA_SET_PRODUCT_SUGGESTIONS';
export const SET_VOICE_INPUT_SERVICE_AVAILABILITY =
  'PIA_SET_VOICE_INPUT_SERVICE_AVAILABILITY';
export const SET_CURRENT_PRODUCTS_LIST = 'PIA_SET_CURRENT_PRODUCTS_LIST';

export const SET_CURRENT_INPUT_PRODUCTS_SUGGESTIONS =
  'PIA_SET_CURRENT_INPUT_PRODUCTS_SUGGESTIONS';
export const SET_RANDOM_PRODUCTS_SUGGESTIONS =
  'PIA_SET_RANDOM_PRODUCTS_SUGGESTIONS';
