const categoriesTableInitialData = {
  idPrefix: Number.MAX_SAFE_INTEGER,
  categories: [
    {
      id: Number.MAX_SAFE_INTEGER - 1,
      name: 'Другое',
      color: '#c0c0c0',
      editable: false,
      translationMark: 'categories_other',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 2,
      name: 'Продукты',
      color: '#ff8000',
      editable: false,
      translationMark: 'categories_products',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 3,
      name: 'Игрушки',
      color: '#9900cc',
      editable: false,
      translationMark: 'categories_toys',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 4,
      name: 'Товары для дома',
      color: '#ffff00',
      editable: false,
      translationMark: 'categories_homewares',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 5,
      name: 'Мебель',
      color: '#663300',
      editable: false,
      translationMark: 'categories_furniture',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 6,
      name: 'Авто',
      color: '#3399ff',
      editable: false,
      translationMark: 'categories_car',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 7,
      name: 'Бытовая техника',
      color: '#99ccff',
      editable: false,
      translationMark: 'categories_home_appliances',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 8,
      name: 'Электроника',
      color: '#0073e6',
      editable: false,
      translationMark: 'categories_electronics',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 9,
      name: 'Спорт и отдых',
      color: '#ffccff',
      editable: false,
      translationMark: 'categories_sport_and_vacation',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 10,
      name: 'Хозтовары',
      color: '#333300',
      editable: false,
      translationMark: 'categories_household_goods',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 11,
      name: 'Красота и здоровье',
      color: '#ff0066',
      editable: false,
      translationMark: 'categories_beauty_and_health',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 12,
      name: 'Одежда и обувь',
      color: '#660033',
      editable: false,
      translationMark: 'categories_clothing_and_shoes',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 13,
      name: 'Дача и сад',
      color: '#00cc66',
      editable: false,
      translationMark: 'categories_garden',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 14,
      name: 'Ремонт',
      color: '#476b6b',
      editable: false,
      translationMark: 'categories_repair',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 15,
      name: 'Зоотовары',
      color: '#ffffcc',
      editable: false,
      translationMark: 'categories_pet',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 16,
      name: 'Канцтовары',
      color: '#339966',
      editable: false,
      translationMark: 'categories_office_supplies',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 17,
      name: 'Книги',
      color: '#993300',
      editable: false,
      translationMark: 'categories_books',
    },
    {
      id: Number.MAX_SAFE_INTEGER - 18,
      name: 'Досуг и хобби',
      color: '#99d6ff',
      editable: false,
      translationMark: 'categories_hobby',
    },
  ],
};

export default categoriesTableInitialData;
